version: 2
jobs:
  build:
    working_directory: ~/galileo
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
    - run:
        name: Build
        command: ./gradlew build

  test:
      working_directory: ~/galileo
      docker:
      - image: circleci/android:api-25-alpha
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
      - checkout
      - run:
        name: Run Tests
        command: ./gradlew lint test
      - store_artifacts:
          path: galileo/build/reports
          destination: reports
      - store_test_results:
          path: galileo/build/test-results

  deploy:
    working_directory: ~/galileo
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - run:
      name: Run Tests
      command: ./gradlew clean install
    - run:
      name: Upload to bintray
      command: ./gradlew :galileo:bintrayUpload :galileo-no-op:bintrayUpload

workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build:
    - test:
        requires:
        - build
        filters:  # required since `deploy` has tag filters AND requires `test`
          tags:
            only: /(\d+\.)(\d+\.)(\d+)/
    - deploy:
        requires:
        - test
        filters:
          tags:
            only: /(\d+\.)(\d+\.)(\d+)/
          branches:
            ignore: /.*/
