version: 2
jobs:
  build:
    working_directory: ~/galileo
    docker:
    - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
    - run:
        name: Build
        command: ./gradlew build

  test:
      working_directory: ~/galileo
      docker:
      - image: circleci/android:api-25-alpha
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
      - run:
          name: Setup emulator
          command: |
            # echo "Listing of /opt/android/sdk"
            # ls /opt/android/sdk
            # I tried API 25 but it is too slow and times out on Circle CI
            set -e
            sdkmanager "system-images;android-22;default;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait for emulator
          command: circle-android wait-for-boot
      - run:
          name: Run Tests
          command: ./gradlew lint jacocoTestReport
      - save_cache:
          paths:
          - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
      - store_artifacts:
          path: galileo/build/reports
          destination: reports
      - store_test_results:
          path: galileo/build/test-results
      - run:
          name: Save code coverage
          command: bash <(curl -s https://codecov.io/bash)

  deploy:
    working_directory: ~/galileo
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
    - run:
        name: Install
        command: ./gradlew clean install
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}
    - run:
        name: Upload to bintray
        command: ./gradlew :galileo:bintrayUpload :galileo-no-op:bintrayUpload

workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - test:
        requires:
        - build
        filters:
          tags:
            only: /.*/
    - deploy:
        requires:
        - test
        filters:
          tags:
            only: /.*/
          branches:
            ignore: /.*/
