defaults: &defaults
  working_directory: ~/galileo
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m

restorecache: &restorecache
  - restore_cache:
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}

savecache: &savecache
  - save_cache:
      paths:
      - ~/.gradle
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "galileo/build.gradle" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    <<: *restorecache
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    <<: *savecache
    - run:
        name: Build
        command: ./gradlew build

  test:
    <<: *defaults
      steps:
      - checkout
      <<: *restorecache
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: galileo/build/reports
          destination: reports
      - store_test_results:
          path: galileo/build/test-results

  deploy:
    <<: *defaults
    steps:
    - checkout
    <<: *restorecache
    - run:
        name: Install
        command: ./gradlew clean install
    - run:
        name: Upload to bintray
        command: ./gradlew :galileo:bintrayUpload :galileo-no-op:bintrayUpload

workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - test:
        requires:
        - build
        filters:
          tags:
            only: /.*/
    - deploy:
        requires:
        - test
        filters:
          tags:
            only: /.*/
          branches:
            ignore: /.*/
